# Site settings
title: Michael Kotlikov's Blog
description: Thoughts and insights about technology and software development
author: Michael Kotlikov
repository: mkotlikov/mkotlikov.github.io

# Build settings
theme: jekyll-theme-primer  # Changed to a theme without sidebar
markdown: kramdown          # The markdown processor
permalink: /posts/:year-:month-:day-:title  # URL structure for posts

# Optional settings
timezone: UTC
encoding: utf-8
future: true      # Allow posts with future dates to be shown
show_excerpts: true  # Show post excerpts on the home page